# Generated by Django 4.1.3 on 2022-11-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='lieu',
            field=models.CharField(default='0000000', max_length=50),
        ),
    ]
