# Generated by Django 2.2.11 on 2022-11-10 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0002_employees_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='dateDeDemarrage',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employees',
            name='natureDuPoste',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='employees',
            name='refAcces',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='employees',
            name='refOrdi',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='employees',
            name='refPhone',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='departement',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='lieu',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='nom',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='prenom',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
