# Generated by Django 4.1.3 on 2022-11-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0003_auto_20221110_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='dateDeDemarrage',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='lieu',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='natureDuPoste',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='employees',
            name='refAcces',
            field=models.CharField(default='here', max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='refOrdi',
            field=models.CharField(default='here', max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='refPhone',
            field=models.CharField(default='here', max_length=50),
        ),
    ]
